name: Generate Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ashutosh00710/github-readme-activity-graph@v1.0.0
        with:
          GH_USERNAME: ${{ github.repository_owner }}
          OUTPUT: dist/activity-graph.svg # Save the file in a dist folder
          THEME: github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
